#!/bin/bash

set -e

REPO_NAME="$(basename "$(git rev-parse --show-toplevel)")"
if [[ $(basename "$PWD") != "$REPO_NAME" ]]; then
  echo "Please run this script from the root repo's directory: '$REPO_NAME'"
  echo "Current directory: $PWD"
  exit 1
fi

PARAMS="${*}"
echo "Running tests with params: $PARAMS"
cd e2e
FRONTEND_URL=https://myapp.dev.localhost ./node_modules/.bin/jest --verbose --forceExit "$PARAMS"
