FROM node:14.17-alpine as nodebuild

ARG VITE_BUILD_NUMBER
ARG VITE_BACKEND_API

WORKDIR /frontend

RUN npm i -g pnpm@6.32

ENV PATH /frontend/node_modules/.bin:$PATH
ENV CI true

COPY pnpm-lock.yaml /frontend

# https://pnpm.io/cli/fetch
RUN --mount=type=cache,target=/root/.pnpm-store \
  pnpm fetch
COPY . /frontend
RUN pnpm install -r --offline

ENV VITE_BUILD_NUMBER=$VITE_BUILD_NUMBER
ENV VITE_BACKEND_API=$VITE_BACKEND_API

RUN mv /frontend/.env.e2e /frontend/.env.production

RUN pnpm run build --unsafe-perm

FROM nginx:stable-alpine

COPY --from=nodebuild /frontend/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
