FROM node:14.17-alpine as nodebuild

ARG REACT_APP_BUILD_NUMBER
ARG REACT_APP_REMOTE_SERVER_URL

WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH
ENV CI true

# install app dependencies
COPY . /frontend

COPY .yarn/ /frontend/.yarn/
COPY package.json /frontend
COPY yarn.lock /frontend
COPY .yarnrc.yml /frontend
COPY .yarn/releases/yarn-3.0.2.cjs /frontend/.yarn/releases/

RUN yarn set version berry
RUN yarn set version 3.0.2
RUN yarn install --immutable

RUN yarn test

ENV REACT_APP_BUILD_NUMBER=$REACT_APP_BUILD_NUMBER
ENV REACT_APP_REMOTE_SERVER_URL=$REACT_APP_REMOTE_SERVER_URL

RUN yarn build

# production environment
# nginx is merely used as a web server (better alt than node) to serve static files, with traefik in front as RP
FROM nginx:stable-alpine
# react-router fix
# WARNING in azure pipeline:
# /bin/docker pull =nodebuild /frontend/build /usr/share/nginx/html
# invalid reference format
COPY --from=nodebuild /frontend/build /usr/share/nginx/html
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

# don't self-daemonize in a container
CMD ["nginx", "-g", "daemon off;"]
