version: "3.8"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: json-file

services:
  backend:
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.api.server:app --bind 0.0.0.0:${BACKEND_PORT:?not set}

  db:
    volumes:
      - myapp_pg_data_prod:/var/lib/postgresql/data/
      - ./backend/.env:/backend/.env
      - ./fts-postgres.conf:/etc/postgresql/postgresql.conf
      - ./.psqlrc:/var/lib/postgresql/.psqlrc

  pg_hero_prod:
    image: ankane/pghero:latest
    container_name: pg_hero_prod
    network_mode: "host"
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:${DB_PORT:?not set}/postgres?sslmode=disable
      PORT: ${PG_HERO_PORT:?not set}
    logging: *default-logging

volumes:
  myapp_pg_data_prod:
