version: "3.8"
services:
  backend:
    command: bash -c "BACKEND_PORT=$$BACKEND_PORT APP_ENV=$$APP_ENV python -m app.api.server"

  frontend:
    volumes:
      - ./frontend/:/frontend/

  db:
    volumes:
      - myapp_pg_data_dev:/var/lib/postgresql/data/
      - ./backend/.env.${APP_ENV:?not set}:/backend/.env.${APP_ENV:?not set}
      - ./fts-postgres.conf:/etc/postgresql/postgresql.conf
      - ./.psqlrc:/var/lib/postgresql/.psqlrc

volumes:
  myapp_pg_data_dev:
