version: "3.8"
x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "2"
  driver: json-file

services:
  frontend_e2e:
    container_name: frontend_${PROJECT_PREFIX:?not set}_e2e
    networks:
      - traefik-net
    build:
      context: ./frontend
      dockerfile: Dockerfile.e2e
      args:
        - "VITE_BACKEND_API=${BACKEND_API}"
        - "VITE_BUILD_NUMBER=${BUILD_NUMBER:?not set}"
    # won't get injected in build
    env_file:
      - ./.env
    restart: unless-stopped
    labels:
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_PREFIX:?not set}-e2e-frontend.rule=Host(`myapp.e2e.localhost`)
      # we're using nginx in the Dockerfile -> 80
      - traefik.port=80
      - traefik.docker.network=traefik-net
      - traefik.http.routers.${PROJECT_PREFIX:?not set}-e2e-frontend.entrypoints=websecure
      - traefik.http.routers.${PROJECT_PREFIX:?not set}-e2e-frontend.tls=true
      - traefik.http.services.${PROJECT_PREFIX:?not set}-e2e-frontend.loadbalancer.server.port=80
    logging: *default-logging

networks:
  traefik-net:
    name: traefik-net
    external: true
