// Code generated by sqlc. DO NOT EDIT.

package main

import (
	"database/sql"
)

type Names struct {
	Nconst             sql.NullString `db:"nconst"`
	PrimaryName        sql.NullString `db:"primary_name"`
	BirthYear          sql.NullString `db:"birth_year"`
	DeathYear          sql.NullString `db:"death_year"`
	PrimaryProfessions []string       `db:"primary_professions"`
	KnownForTitles     []string       `db:"known_for_titles"`
}
