version: "3.8"

services:
  # nginx:
  #   container_name: nginx
  #   image: jwilder/nginx-proxy
  #   ports:
  #     - 0.0.0.0:80:80
  #     - 0.0.0.0:443:443
  #   networks:
  #     - internet
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./statup/nginx/certs:/etc/nginx/certs:ro
  #     - ./statup/nginx/vhost:/etc/nginx/vhost.d
  #     - ./statup/nginx/html:/usr/share/nginx/html:ro
  #     - ./statup/nginx/dhparam:/etc/nginx/dhparam
  #   environment:
  #     DEFAULT_HOST: localhost

  # TODO traefik net and labels to be able to ping?
  statup:
    container_name: statup
    image: statping/statping:latest
    restart: always
    networks:
      - internet
      - database
    depends_on:
      - postgres
    volumes:
      - ./statup/app:/app
    environment:
      VIRTUAL_HOST: localhost
      VIRTUAL_PORT: 8080
      DB_CONN: postgres
      DB_HOST: postgres
      DB_USER: statup
      DB_PASS: password123
      DB_DATABASE: statup
      NAME: EC2 Example
      DESCRIPTION: This is a Statping Docker Compose instance
    ports:
      - 8880:8080

  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    networks:
      - database
    volumes:
      - ./statup/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: statup
      POSTGRES_DB: statup

networks:
  internet:
    driver: bridge
  database:
    driver: bridge
