http:
  routers:
    traefik:
      rule: "Host(`traefik.app.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "app.localhost"
            sans:
              - "*.app.localhost"
          - main: "domain.local"
            sans:
              - "*.domain.local"

tls:
  certificates:
    # provide container mount path
    - certFile: "/etc/certs/localhost.pem"
      keyFile: "/etc/certs/localhost-key.pem"
