/**
 * Snapshot data for unit and integration tests.
 * Update regularly after feature updates, do not type check as its an unnecessary burden
 */
export const testInitialState = {
  auth: {
    isLoading: false,
    isUpdating: false,
    isAuthenticated: true,
    error: null,
    pwdResetError: null,
    userLoaded: true,
    user: {
      email: 'testuser2@mail.com',
      username: 'testuser2',
      is_verified: true,
      is_active: true,
      is_superuser: false,
      role: 'user',
      last_notification_at: '2021-11-16T21:43:58.916862',
      created_at: '2021-11-16T21:20:29.709695',
      updated_at: '2021-11-16T21:43:58.930945',
      id: 7,
      access_token: null,
      profile: {
        full_name: null,
        phone_number: null,
        bio: null,
        image: null,
        created_at: '2021-11-16T21:20:29.719685',
        updated_at: '2021-11-16T21:20:29.719685',
        id: 7,
        user_id: 7,
        username: null,
        email: null,
      },
    },
  },
  ui: {
    toastList: [],
  },
  userProfile: {
    isLoading: false,
    isUpdating: false,
    isUpdated: false,
    error: null,
    userLoaded: false,
    user: {
      id: null,
    },
  },
  admin: {
    isLoading: false,
    isUpdating: false,
    error: null,
    data: {},
  },
  feed: {
    globalNotifications: {
      data: [
        {
          row_number: 1,
          event_timestamp: '2021-11-16T21:20:33.956387',
          id: 20,
          created_at: '2021-11-16T21:20:33.956387',
          updated_at: '2021-11-16T21:20:33.956387',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 19',
          body: '\n                This is test notification 19.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 19',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 2,
          event_timestamp: '2021-11-16T21:20:33.947414',
          id: 19,
          created_at: '2021-11-16T21:20:33.947414',
          updated_at: '2021-11-16T21:20:33.947414',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 18',
          body: '\n                This is test notification 18.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 18',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 3,
          event_timestamp: '2021-11-16T21:20:33.937192',
          id: 18,
          created_at: '2021-11-16T21:20:33.937192',
          updated_at: '2021-11-16T21:20:33.937192',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 17',
          body: '\n                This is test notification 17.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 17',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 4,
          event_timestamp: '2021-11-16T21:20:33.931373',
          id: 17,
          created_at: '2021-11-16T21:20:33.931373',
          updated_at: '2021-11-16T21:20:33.931373',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 16',
          body: '\n                This is test notification 16.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 16',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 5,
          event_timestamp: '2021-11-16T21:20:33.916935',
          id: 16,
          created_at: '2021-11-16T21:20:33.916935',
          updated_at: '2021-11-16T21:20:33.916935',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 15',
          body: '\n                This is test notification 15.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 15',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 6,
          event_timestamp: '2021-11-16T21:20:33.904861',
          id: 15,
          created_at: '2021-11-16T21:20:33.904861',
          updated_at: '2021-11-16T21:20:33.904861',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 14',
          body: '\n                This is test notification 14.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 14',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 7,
          event_timestamp: '2021-11-16T21:20:33.897457',
          id: 14,
          created_at: '2021-11-16T21:20:33.897457',
          updated_at: '2021-11-16T21:20:33.897457',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 13',
          body: '\n                This is test notification 13.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 13',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 8,
          event_timestamp: '2021-11-16T21:20:33.889998',
          id: 13,
          created_at: '2021-11-16T21:20:33.889998',
          updated_at: '2021-11-16T21:20:33.889998',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 12',
          body: '\n                This is test notification 12.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 12',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 9,
          event_timestamp: '2021-11-16T21:20:33.882671',
          id: 12,
          created_at: '2021-11-16T21:20:33.882671',
          updated_at: '2021-11-16T21:20:33.882671',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 11',
          body: '\n                This is test notification 11.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 11',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
        {
          row_number: 10,
          event_timestamp: '2021-11-16T21:20:33.871833',
          id: 11,
          created_at: '2021-11-16T21:20:33.871833',
          updated_at: '2021-11-16T21:20:33.871833',
          sender: 'admin@myapp.com',
          receiver_role: 'user',
          title: 'Test notification 10',
          body: '\n                This is test notification 10.\n\n                As you can observe the body is getting bigger as I write this unnecessarily long sentence but it should\n                come out nicely in the frontend nevertheless.\n                ',
          label: 'Test label 10',
          link: 'https://www.google.com',
          event_type: 'is_create',
        },
      ],
      unreadData: [],
      canLoadMore: true,
      hasNewNotifications: false,
      isLoading: false,
      error: null,
    },
  },
}
