package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
)

// UpdateUpdatedAtColumn calls the stored function 'public.update_updated_at_column() trigger' on db.
func UpdateUpdatedAtColumn(ctx context.Context, db DB) (Trigger, error) {
	// call public.update_updated_at_column
	const sqlstr = `SELECT * FROM public.update_updated_at_column()`
	// run
	var r0 Trigger
	logf(sqlstr)
	if err := db.QueryRowContext(ctx, sqlstr).Scan(&r0); err != nil {
		return Trigger{}, logerror(err)
	}
	return r0, nil
}
